services:
  frontend:
    container_name: co2-app
    image: frontend-co2-app
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend_prod:/app

  nginx:
    image: co2-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend